<a href="https://colab.research.google.com/github/baisakhi-7/baisakhi_2201206011/blob/main/1st_PYTHON_22_2_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hello',end='')
print("cse")

hellocse


In [ ]:
a=100
print("a=",a)

a= 100


In [ ]:
n=input('Enter you name')
print('myself' ,n)


Enter you nameBaisakhi
myself Baisakhi


In [ ]:
#Arith

In [ ]:
#Addition of two nos from key board
a =int (input('Enter 1st no'))
b =int (input('Enter 2nd no'))
c = a + b
print('a+b=',c)

Enter 1st no11
Enter 2nd no20
a+b= 31


In [ ]:
print('welcome to my first program')


welcome to my first program


In [ ]:
# to checkdata type
a=100
b=10.5
c='ABIT'
d=True
print =('Type of a=',type(a))
print =('Type of b=',type(b))
print =('Type of c=',type(c))
print =('Type of d=',type(d))

In [ ]:
a = 8
b = 5
d= a != b,
print ('a !=b=',d)

a !=b= (True,)


In [ ]:
a=2
b=5
a+=b
print('a=',a)
print('b=',b)

a= 7
b= 5


In [ ]:
#Special Operator
a=5
b=5
d=a is b
print('a is b=',d)
d = a is not b
print('a is not b',d)

a is b= True
a is not b False


In [ ]:
# in and not in operator
a ="hello"
b = "1"
c = b in a
print ('b in a=',c)
d = b not in a
print('b not in a =',d)

b in a= False
b not in a = True


In [ ]:
# input a no and check even.
a = int(input('enter a no'))
if a%2==0:
 print ('even no')

enter a no26 
even no


In [ ]:
str = 'BAISAKHI'
for i in str:
   print(i)

B
A
I
S
A
K
H
I


In [ ]:
for i in range (1,11):
 print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
n = int (input ('n = ?'))
c=0
for i in range (1,n+1):
   if(1%2==1;)
    c=c+1
    print(i,end=',')
    print('No of ODD=',c)


In [ ]:
# while loop
n = i
while n<=10:
   print(n)
   n=n+1

10


In [ ]:
unsorted_list=[5,4,-3,7,99]
sorted_list=sorted(unsorted_list)
print("sorted list:",sorted_list)


sorted list: [-3, 4, 5, 7, 99]


In [ ]:
import numpy as np
data2 = [[1,2,3,4],[5,5,7,8]]
arr2 = np.array(data2)
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [ ]:
import numpy as np
data2 = [[1,2,3,4],[5,6,7,8],[55,66,76,88]]
arr2 = np.array(data2)
print(arr2.ndim)
print(arr2.shape)
print(arr2) import numpy as np

In [ ]:
a = np.array([[0,1,2],[2,3,4]])
a

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
array = np.arange(0,10,2)
a

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
array = np.random.randint(0,10,(3,3))
a

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
arr = np.array([[1.,2.,3],[4.,5.,6]])
print(arr)
[(1,2,3)]

[[1. 2. 3.]
 [4. 5. 6.]]


[(1, 2, 3)]

In [ ]:
def gcd_fun(x,y):
 if(y==0):#
   return x
 else:
   return gcd_fun(y,x%y)
x = int(input("enter the first number"))
y= int(input("enter the second number"))
num=gcd_fun(x,y)
print("GCD of two numbers is:")
print(num) #call num

enter the first number60
enter the second number90
GCD of two numbers is:
30


In [ ]:
def linear_search(list,n,key)
for i in range(0,n)
    if(list1[i] == key):
       return i
       return-1
       list 1 = [1,3,5,4,7,9]
       key = 7
       n=len(list1)
       res=linear_search(list1,n,key)
       if(res==-1):

         print("element found at index",res)

